#!/bin/bash
export XDMFWRITER_ALIGNMENT=4096 
export XDMFWRITER_BLOCK_SIZE=4096 
export SEISSOL_CHECKPOINT_ALIGNMENT=4096 
export SEISSOL_CHECKPOINT_DIRECT=1  
export ASYNC_MODE=THREAD 
export ASYNC_BUFFER_ALIGNMENT=4096
